version: 2.1

orbs:
  docker: circleci/docker@2.0
  heroku: circleci/heroku@2.0
  python: circleci/python@2.0

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo service docker start
      - run:
          name: Build Docker Image
          command: |
            docker build --platform linux/amd64 -t registry.heroku.com/${HEROKU_APP_NAME}/web .
      - run:
          name: Push Docker Image
          command: |
            echo "${HEROKU_API_KEY}" | docker login --username _ --password-stdin registry.heroku.com
            docker push registry.heroku.com/${HEROKU_APP_NAME}/web
  deploy:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: |
            echo "${HEROKU_API_KEY}" | heroku auth:token
            heroku container:release web --app ${HEROKU_APP_NAME}
workflows:
  version: 2
  deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build